### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by ManuelStapper** [MFaymon/spINAR#4]
Hi there,

I reviewed your package/paper and genuinely enjoyed learning about the topic and testing the package.  There are a few comments and questions, I'd like to address regarding my review checklist:

- Scholarly effort: The package is probably flagged for inspection by the editors due to <1000 LOC (according to codecov), but I see the effort in structuring the package and the rather complex theory. However, I was wondering if there had been previous work you relied on? I.e  an implementation of methods by Carsten Jentsch and Christian Weiß from their 2019 paper on the Bootstrap procedure? Or am implementation by Drost et al.?

- Performance: You state (around line 48 of the paper) that your main contribution is the efficient semiparametric estimation. It is not clear to me whether "efficient" refers to the properties of the estimators or the implementation of estimation. 

- Statement of Need: In my opinion the SoN in your paper and/or documentation would greatly benefit if you mentioned an application example. Did other authors maybe even discuss an application in which the semiparametric estimation is superior to a parametric approach (as that's your focus)?

-  Statement of Need / State of field: You mentioned that INAR processes are "clearly the most popular" among observation-driven count data models (around line 11 of the paper). On what basis do you make the statement? And related question: Is there actually no implementation in R dealing with INAR models, at least for parametric estimation? That would be in contrast with above popularity statement, wouldn't it? For example the tscount package has been applied and cited quite a few times.

- Community guidelines: JOSS suggests to give the target audience information on how to contribute and how to get support. I think it would be a great idea to include a note in your Repo.

- Outlook: I am very curious about how the package will develop in the future. If you have any plans, maybe you could list them in the Repo's readme. My suggestion would be to cover INAR(p) processes or arbitrary order by implementing a general likelihood function and leave the choice to the users. 

Looking forward to hearing from you.
All the best and keep up the good work!

**Comment by MFaymon** [comment]
> Community guidelines: JOSS suggests to give the target audience information on how to contribute and how to get support. I think it would be a great idea to include a note in your Repo.

Thanks for the suggestion. I included a note in the Readme, see 8283b92.

**Comment by MFaymon** [comment]
> Outlook: I am very curious about how the package will develop in the future. If you have any plans, maybe you could list them in the Repo's readme. My suggestion would be to cover INAR(p) processes or arbitrary order by implementing a general likelihood function and leave the choice to the users.

I added a possible extension to the Readme, see ea325f7 and dc3168c, which came to our mind during writing the package. It contains a generalization of the INAR model class.

We do not see much benefit in the inclusion of higher order INAR models ($p >2$) in our package since mostly only INAR models of order $p \in \{ 1,2 \}$ find application in the literature.

**Comment by MFaymon** [comment]
> Scholarly effort: The package is probably flagged for inspection by the editors due to <1000 LOC (according to codecov), but I see the effort in structuring the package and the rather complex theory. However, I was wondering if there had been previous work you relied on? I.e an implementation of methods by Carsten Jentsch and Christian Weiß from their 2019 paper on the Bootstrap procedure? Or am implementation by Drost et al.?

Thanks for bringing it up! We don‘t use any implementation of Drost et al. but we relied on some excerpt of code from Christian Weiß. After consultation with him, I added him as contributor of our package, see 6adef07.

**Comment by MFaymon** [comment]
> Performance: You state (around line 48 of the paper) that your main contribution is the efficient semiparametric estimation. It is not clear to me whether "efficient" refers to the properties of the estimators or the implementation of estimation.

Efficiency is a property of the semiparametric estimator, see [Drost et al. (2009)](https://doi.org/10.1111/j.1467-9868.2008.00687.x). To avoid misunderstandings, I have changed the wording in the paper, see 216657b.

**Comment by MFaymon** [comment]
> Statement of Need / State of field: You mentioned that INAR processes are "clearly the most popular" among observation-driven count data models (around line 11 of the paper). On what basis do you make the statement? And related question: Is there actually no implementation in R dealing with INAR models, at least for parametric estimation? That would be in contrast with above popularity statement, wouldn't it? For example the tscount package has been applied and cited quite a few times.

Thanks for pointing out that a source is missing there. I have weakened the statement a little and added a source citation, see 4e1a153.

As already mentioned, the R package tscount only deals with parameter-driven count data time series models. INAR models don’t belong to this model class. But I found a recent R packages which allows to simulate and estimate INAR(p) data by using MCMC algorithms. The package is limited to the parametric setup, where the innovations are assumed to follow either a Poisson or a zero-inflated Poisson distribution. I now cite it in the paper, see 190e847.

**Comment by MFaymon** [comment]
> Statement of Need: In my opinion the SoN in your paper and/or documentation would greatly benefit if you mentioned an application example. Did other authors maybe even discuss an application in which the semiparametric estimation is superior to a parametric approach (as that's your focus)?

Thanks for this valuable comment! The paper now mentions several application examples and I added a discussion which emphasizes the benefit of the semiparametric estimation approach, see 62eefde.
